# Generated by Django 3.1.1 on 2020-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, help_text="Enter field name")),
                ('age', models.IntegerField(help_text="Enter field age", blank=False)),
                ('address', models.CharField(max_length=20, help_text="Enter field address", blank=False)),
                ('work', models.CharField(max_length=20, help_text="Enter field address", blank=False)),
            ],
        ),
    ]
