# Generated by Django 3.1.1 on 2020-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.CharField(default=1, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
