# Generated by Django 3.1.1 on 2020-09-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, help_text='Enter field address', max_length=20, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, help_text='Enter field age', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Enter field name', max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='work',
            field=models.CharField(blank=True, help_text='Enter field address', max_length=20, verbose_name='Работа'),
        ),
    ]
