# Generated by Django 3.1.1 on 2020-09-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter field name', max_length=20, verbose_name='Имя')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('address', models.CharField(default='', max_length=20, verbose_name='Адресс')),
                ('work', models.CharField(default='', max_length=20, verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['id'],
            },
        ),
    ]
